# Scores Generation File

1. Generates the Old Regression score summary & saves the file into ./Score Summary/df_score_summary_old_reg.csv
2. Generates the New Regression score summary & saves the file into ./Score Summary/df_score_summary_new_reg.csv

In [1]:
# Install the necessary packages from "_packages_startup.txt"

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats
import datetime as dt
import itertools as it
import ast

import sys
sys.path.append('../src')
from utils import *

In [6]:
# Import the price data from "../Raw Data/ETF_PriceFile_2017_to_2025.csv"
df_price_all = pd.read_csv('../Raw Data/ETF_PriceFile_2017_to_2025.csv', index_col=0)

In [8]:
# Dates are in Excel Date format. Arrange them in descending order to send generate scores. Then view the input to confirm!
df_price_all.sort_index(ascending=False, inplace=True)
df_price_all.head(5)

,ACWV US Equity,AGG US Equity,AMLP US Equity,ARKG US Equity,ARKK US Equity,ARKQ US Equity,ASHR US Equity,BBAX US Equity,BNDX US Equity,BOTZ US Equity,...,XLE US Equity,XLF US Equity,XLI US Equity,XLK US Equity,XLP US Equity,XLU US Equity,XLV US Equity,XLY US Equity,XME US Equity,XOP US Equity
DATE,,,,,,,,,,,,,,,,,,,,,
45728.0,135.600733,121.743982,101.962778,24.833594,53.358143,71.406122,29.708764,64.588994,61.389655,31.631585,...,124.493695,55.618077,149.954249,231.159918,98.823750,99.735835,165.227240,214.352721,62.418239,145.240856
45727.0,136.317312,122.103584,101.521814,24.271405,51.830859,69.982673,29.774784,64.536376,61.288206,31.197426,...,123.926397,55.536423,149.965774,227.578075,101.018455,100.046015,166.895509,213.115633,62.160683,143.746896
45726.0,137.631042,122.537587,101.221157,23.774085,51.475927,70.705020,29.389670,64.773158,61.503786,31.001021,...,124.919169,56.014683,152.305388,228.506297,102.518791,100.989479,168.735176,215.220854,60.257005,143.023260
45723.0,138.407336,121.954784,100.880413,25.222801,56.412711,74.348623,29.741774,65.957071,61.491105,32.293161,...,123.997309,57.297818,154.725678,238.651212,102.741981,99.890925,170.574843,223.185968,62.720588,143.046603
45722.0,137.368296,122.103584,99.497391,25.103877,56.079290,73.594408,29.972842,66.154389,61.491105,32.003721,...,121.912486,57.601104,152.939273,235.244093,102.407196,98.068617,170.563417,223.598331,63.146116,140.642262

In [9]:
# Generate the Old Regression Summary dataframe. The regression_array list can be found under documentation in  ../src/utils.py 

regression_array_old = list(range(10, 126, 5))
df_score_summary_old_reg = Regression_Gen(df_price_all, regression_array_old)

In [11]:
# Generate the New Regression Summary dataframe. The regression_array list can be found under documentation in  ../src/utils.py

regression_array_current = [25, 30, 40, 55, 75, 100, 130, 165, 205, 250]
df_score_summary_new_reg = Regression_Gen(df_price_all, regression_array_current)

In [13]:
# Set the index to 'Date' for both dataframes
df_score_summary_old_reg.set_index('Date', inplace=True)
df_score_summary_new_reg.set_index('Date', inplace=True)

# Export the Score Summary dataframes to CSV files in "../Score Summary/df_score_summary_old_reg.csv" and "../Score Summary/df_score_summary_new_reg.csv"
df_score_summary_old_reg.to_csv('../Score Summary/df_score_summary_old_reg.csv')
df_score_summary_new_reg.to_csv('../Score Summary/df_score_summary_new_reg.csv')